
auth_enabled: false

server:
  http_listen_port: 3100

common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /loki

schema_config:
  configs:
  - from: 2020-05-15
    store: tsdb
    object_store: filesystem
    schema: v13
    index:
      prefix: index_
      period: 24h

limits_config: 
  retention_period: 672h   # 28 дней


storage_config:
  filesystem:
    directory: /loki/chunks

frontend:
  encoding: protobuf

ruler:
  evaluation_interval: 30s
  storage:
    type: local
    local:
      directory: /etc/loki/rules
  rule_path: /etc/loki/scratch
  alertmanager_url: http://alertmanager:9093
  ring:
    kvstore:
      store: inmemory
  enable_api: true
