global:
  resolve_timeout: 2m  # Время ожидания для подтверждения разрешения алерта.

templates:
  - '/etc/alertmanager/templates/telegram_msg.tmpl'  # Укажите путь к файлу с шаблоном
  
route:
  group_by: ['server'] 
  receiver: 'telegram'  # Уведомления по умолчанию будут отправляться
  
  routes:
    - match:
        severity: 'Critical'  # Алерты с критической важностью.
      receiver: 'telegram'  # Получатель для критических алертов.
      group_wait: 10s  # Время ожидания для сбора алертов до отправки первого уведомления для критических.
      group_interval: 5s  # Интервал между группами уведомлений для критических.
      repeat_interval: 5m  # Интервал повторных уведомлений для критических.
      resolve_timeout: 2m  # Время ожидания для уведомления о решении предупреждения.

    - match:
        severity: 'Warning'  # Алерты с предупреждением.
      receiver: 'telegram2'  # Получатель для предупреждений.
      group_wait: 10s  # Время ожидания для сбора алертов до отправки первого уведомления для предупреждений.
      group_interval: 5s  # Интервал между группами уведомлений для предупреждений.
      repeat_interval: 1h  # Интервал повторных уведомлений для предупреждений.
      resolve_timeout: 2m  # Время ожидания для уведомления о решении предупреждения.
receivers:
  - name: 'telegram'
    telegram_configs:
      - chat_id: -  # Замените на ваш Chat ID
        bot_token: ''  # Замените на ваш Telegram Bot Token
        send_resolved: true
        message: '{{ template "telegram.message" . }}'
  - name: 'telegram2'
    telegram_configs:
      - chat_id: - # Замените на ваш Chat ID
        bot_token: ''  # Замените на ваш Telegram Bot Token
        send_resolved: false  # Не отправлять уведомления о resolved.
        message: '{{ template "telegram2.message" . }}'
#https://api.telegram.org/botTHERE_TOKEN/getUpdates 

 # tz "Etc/GMT-5" = часовой пояс +5, изменить на нужный 

