groups:
  - name: example-alerts  # Имя группы алертов
    rules:

      - alert: HIGH_CPU_USAGE  # Название алерта
        expr:  1 - (sum(rate(node_cpu_seconds_total{mode="idle", job="node_exporter" }[30s])) by (instance, server) / sum(rate(node_cpu_seconds_total{job="node_exporter"}[30s])) by (instance, server)) > 0.9  
        for: 1s  # Если условие выполняется более 1s 
        labels:
          severity: Critical  # Степень важности алерта
        annotations:
          summary: "Нагрузка CPU больше 90 процентов на ноде {{ $labels.server }}"  # Описание алерта
          description: "-"

      - alert: NODE_POWEROFF  
        expr:  up{job='node_exporter'} == 0  
        for: 1s  
        labels:
          severity: Critical  
        annotations:
          summary: "Выклена нода: {{ $labels.server }}"  
          description: "-"
          
      - alert: ZFS_REPLICA_ERROR  
        expr:  pve_replication_failed_syncs{job='proxmox'} > 0 
        for: 1s  
        labels:
          severity: Critical  
        annotations:
          summary: "ВМ или Контейнер с id {{ $labels.id }} имеет проблемы с репликацией на ноде {{ $labels.server }} "    # Описание алерта
          description: "-"

      - alert: ZFS_POOL_ERROR  # Название алерта
        expr:  node_zfs_zpool_state{state!='online',job='node_exporter'} > 0 
        for: 1s  # Если условие выполняется более 1s 
        labels:
          severity: Critical  # Степень важности алерта
        annotations:
          summary: "Пул {{ $labels.zpool }} имеет статус {{ $labels.state }} на ноде - {{ $labels.server }} "    # Описание алерта
          description: "-"

      - alert: HIGH_CPU_USAGE2  # Название алерта
        expr:  1 - (sum(rate(node_cpu_seconds_total{mode="idle", job="node_exporter" }[30s])) by (instance, server) / sum(rate(node_cpu_seconds_total{job="node_exporter"}[30s])) by (instance, server)) > 0.8  
        for: 1s  # Если условие выполняется более 1s 
        labels:
          severity: Critical  # Степень важности алерта
        annotations:
          summary: "Нагрузка CPU больше 80 процентов на ноде {{ $labels.server }}"  # Описание алерта
          description: "-"
