{
 "title": "1. Nodes monitoring (node-exporter)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(node_dmi_info{job=\"node_exporter\"},instance)"
    }
   },
   { "name": "interval", "query": "30s,1m,15s" },
   {
    "name": "disk",
    "query": {
     "query": "label_values(node_disk_write_time_seconds_total,device)"
    }
   },
   {
    "name": "network_interface",
    "query": {
     "query": "label_values(node_network_iface_link,device)"
    }
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "RAM/CPU basic metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Нагрузка на процессор +",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-(sum(rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$node\"}[$interval])) by (server) / sum(rate(node_cpu_seconds_total{ instance=~\"$node\"}[$interval])) by (server))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Сколько RAM всего",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": " {{server}} ram"
    }
   ]
  },
  {
   "title": "сколько GB RAM используется ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemFree_bytes{instance=~\"$node\"} ",
     "legendFormat": "{{server}} "
    }
   ]
  },
  {
   "title": "сколько процентов RAM используется ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemFree_bytes{instance=~\"$node\"}) / node_memory_MemTotal_bytes{instance=~\"$node\"}) ",
     "legendFormat": "{{server}} "
    }
   ]
  },
  { "title": "Disks metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "IO delay процессора",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(node_cpu_seconds_total{mode=\"iowait\",instance=~\"$node\"}[$interval])) by(server)/ sum(increase(node_cpu_seconds_total{instance=~\"$node\"}[$interval])) by(server)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Utilization/%",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=~\"$node\",device=~\"$disk\"}[$interval])",
     "legendFormat": "{{server}} Диск: {{device}}"
    }
   ]
  },
  {
   "title": "Скорость записи/СЕК",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{device=~\"$disk\",instance=~\"$node\"}[$interval])",
     "legendFormat": "{{server}}. Диск: {{device}}"
    }
   ]
  },
  {
   "title": "Скорость чтения/СЕК",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=~\"$disk\",instance=~\"$node\"}[$interval])",
     "legendFormat": "{{server}}. Диск: {{device}}"
    }
   ]
  },
  {
   "title": "Задержка записи/СЕК",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(node_disk_write_time_seconds_total{instance=~\"$node\",device=~\"$disk\"}[$interval])  or 0/ rate(node_disk_writes_completed_total{instance=~\"$node\",device=~\"$disk\"}[$interval])\r\n\r\n",
     "legendFormat": "{{server}}. Диск: {{device}}"
    }
   ]
  },
  {
   "title": "Задержка чтения/СЕК",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{instance=~\"$node\",device=~\"$disk\"}[$interval])  or 0 / rate(node_disk_reads_completed_total{instance=~\"$node\",device=~\"$disk\"}[$interval])\r\n\r\n",
     "legendFormat": "{{server}}. Диск: {{device}}"
    }
   ]
  },
  {
   "title": "FS free space / Свободное место",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{instance=~\"$node\", fstype=~\"zfs|ext4\"}",
     "legendFormat": "{{server}} - {{mountpoint}}"
    }
   ]
  },
  {
   "title": "FS used space / Занятое место",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$node\", fstype=~\"zfs|ext4\"} - node_filesystem_free_bytes{instance=~\"$node\", fstype=\"zfs\"} ",
     "legendFormat": "{{server}} - {{mountpoint}}"
    }
   ]
  },
  { "title": "Network metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Данных приходит/СЕК",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total {instance=~'$node', device=~'$network_interface'}[$interval])",
     "legendFormat": "{{server}} - {{device}}"
    }
   ]
  },
  {
   "title": "Данных уходит/СЕК",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~'$node', device=~'$network_interface'}[$interval])",
     "legendFormat": "{{server}} - {{device}}"
    }
   ]
  },
  {
   "title": "Процент нагрузки на интерфейс",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "\r\n(\r\n  rate(node_network_receive_bytes_total{instance=~'$node', device=~'$network_interface'}[$interval]) \r\n  + \r\n  rate(node_network_transmit_bytes_total{instance=~'$node', device=~'$network_interface'}[$interval])\r\n)\r\n/\r\n(node_network_speed_bytes{instance=~'$node', device=~'$network_interface'}> 0)",
     "legendFormat": "{{server}} {{device}} "
    }
   ]
  },
  {
   "title": "Потери пакетов % из 100  при передаче",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\r\n  rate(node_network_transmit_drop_total{instance=~'$node', device=~'$network_interface'}[$interval])\r\n  /\r\n  rate(node_network_transmit_packets_total{instance=~'$node', device=~'$network_interface'}[$interval])\r\n)",
     "legendFormat": " {{server}} {{device}} - Потери:"
    }
   ]
  },
  {
   "title": "Потери пакетов % из 100 при получении",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\r\n  rate(node_network_receive_drop_total{instance=~'$node', device=~'$network_interface'}[$interval])\r\n  /\r\n  rate(node_network_receive_packets_total{instance=~'$node', device=~'$network_interface'}[$interval])\r\n)",
     "legendFormat": " {{server}} {{device}} - Потери:"
    }
   ]
  },
  { "title": "ZFS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "ZFS ARC % usage / Процент использование ARC ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node_zfs_arc_c{instance=~\"$node\"} / node_zfs_arc_c_max{instance=~\"$node\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "ZFS ARC usage / Зачение node_zfs_arc_c",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_zfs_arc_c{instance=~\"$node\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Max value ZFS ARC / Зачение zfs_arc_max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_zfs_arc_c_max{instance=~\"$node\"} ",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "ARC miss % / процент промахов, при обращении к ARC",
   "type": "timeseries",
   "description": "Он вычисляет отношение промахов ARC к общему количеству обращений к ARC (промахи + попадания). Это метрика, которая показывает, насколько эффективно работает кэш ZFS ARC.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_zfs_arc_misses {instance=~\"$node\"}[$interval]) / (rate(node_zfs_arc_hits{instance=~\"$node\"}[$interval])  + rate(node_zfs_arc_misses{instance=~\"$node\"}[$interval]))",
     "legendFormat": "{{server}}"
    }
   ]
  }
 ]
}