{
 "title": "2. Proxmox metrics monitoring (pve-exporter)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "interval", "query": "30s,1m,15s" },
   {
    "name": "node",
    "query": {
     "query": "label_values(pve_node_info{job=\"proxmox\"},instance)"
    }
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Нагрузка на процессор",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(pve_cpu_usage_ratio{instance=\"$node\"}  * on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1",
     "legendFormat": "{{id}} {{name}} "
    }
   ]
  },
  {
   "title": "Используется оперативной памяти ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(pve_memory_usage_bytes{instance=\"$node\"} / pve_memory_size_bytes * on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1",
     "legendFormat": "{{id}} {{name}} "
    }
   ]
  },
  {
   "title": "Disk IO/s - write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(pve_disk_write_bytes{instance=\"$node\"}[$interval]) \r\n* on(id, instance) group_left(name, type) pve_guest_info\r\nand on(id, instance) pve_up == 1\r\n",
     "legendFormat": "{{id}} {{name}} "
    }
   ]
  },
  {
   "title": "Disk IO/s - read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(pve_disk_read_bytes{instance=\"$node\"}[$interval]) \r\n* on(id, instance) group_left(name, type) pve_guest_info\r\nand on(id, instance) pve_up == 1\r\n",
     "legendFormat": "{{id}} {{name}} "
    }
   ]
  },
  {
   "title": "Network IO/s - Получение данных в секунду",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(rate(pve_network_receive_bytes{instance=\"$node\"}[$interval]) * on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1",
     "legendFormat": "{{id}} {{name}} "
    }
   ]
  },
  {
   "title": "Network IO/s - Отправка данных в секунду",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(rate(pve_network_transmit_bytes{instance=\"$node\"}[$interval]) * on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1",
     "legendFormat": "{{id}} {{name}} "
    }
   ]
  },
  {
   "title": "Replica fails in row / Количество ошибок репликации подряд",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "fails" } },
   "targets": [
    { "expr": "pve_replication_failed_syncs ", "legendFormat": "VM/LXC id: {{id}}" }
   ]
  },
  {
   "title": "Replica duration / Длительность репликации",
   "type": "timeseries",
   "description": "Или последней, или которая еще продолжается",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pve_replication_duration_seconds",
     "legendFormat": "VM/LXC id: {{id}}"
    }
   ]
  },
  {
   "title": "Процент занятого места у пулов",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": " (pve_disk_usage_bytes{instance=\"$node\", id=~\"storage/.+\"} / pve_disk_size_bytes {instance=\"$node\", id=~\"storage/.+\"})",
     "legendFormat": " {{id}}"
    }
   ]
  }
 ]
}