{
 "title": "3. Logs monitoring (loki + promtail metrics)",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   {
    "name": "server",
    "query": {
     "query": "label_values(up{job=\"promtail\"},server)"
    }
   },
   {
    "name": "level",
    "query": "| level=~\"error\" or detected_level=~\"error\", | level=~\"warn\" or detected_level=~\"warn\", | level!~\"warn\" and detected_level!~\"warn\" and level!~\"error\" and detected_level!~\"error\", "
   },
   {
    "name": "logs_from",
    "query": {}
   },
   { "name": "Loki", "query": "loki" },
   { "name": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Отображение логов из переменной $levels",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Selected logs last 30m / Выбранных логов за 30 минут",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (server) (count_over_time({server=~\"$server\", service_name=~\"$logs_from\"}| logfmt  $level [30m])) ",
     "legendFormat": "{{server}} Logs: "
    }
   ]
  },
  {
   "title": "Selected logs last 1h / Выбранных логов за 1 час",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (server) (count_over_time({server=~\"$server\", service_name=~\"$logs_from\"} | logfmt  $level  [1h])) ",
     "legendFormat": "{{server}} Logs: "
    }
   ]
  },
  {
   "title": "Selected logs last 3h / Выбранных логов за 3 часа",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (server) (count_over_time({server=~\"$server\", service_name=~\"$logs_from\"} | logfmt  $level [3h])) ",
     "legendFormat": "{{server}} Logs: "
    }
   ]
  },
  {
   "title": "Selected logs last 6h / Выбранных логов за 6 часов",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (server) (count_over_time({server=~\"$server\", service_name=~\"$logs_from\"} | logfmt  $level [6h])) ",
     "legendFormat": "{{server}} Logs: "
    }
   ]
  },
  {
   "title": "Selected logs last 12h / Выбранных логов за 12 часов",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (server) (count_over_time({server=~\"$server\", service_name=~\"$logs_from\"}| logfmt  $level [12h])) ",
     "legendFormat": "{{server}} Logs: "
    }
   ]
  },
  {
   "title": "Selected logs last 24h / Выбранных логов  за 24 часа",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (server) (count_over_time({server=~\"$server\", service_name=~\"$logs_from\"} | logfmt  $level [24h])) ",
     "legendFormat": "{{server}} Logs: "
    }
   ]
  },
  {
   "title": "Error logs / Логи с ошибками ",
   "type": "logs",
   "description": "Чтобы показывать логи только одного сервера, поменять на верхней панели значение \"server\" на нужный вам",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{server=~\"$server\", service_name=~\"$logs_from\"} | logfmt  $level"
    }
   ]
  }
 ]
}