{
 "title": "99. Localhost node monitoring (cadviso + node_exporter)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "interval", "query": "30s,1m,15s" },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(node_dmi_info{job=\"local_node_exporter\"},instance)"
    }
   },
   {
    "name": "disk",
    "query": {
     "query": "label_values(node_disk_write_time_seconds_total,device)"
    }
   }
  ]
 },
 "panels": [
  { "title": "DOCKER", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{image!=\"\", job=\"local_cadvisor\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{image!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Cached",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_cache{image!=\"\",name=~\".+\"}\r\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "RAM/CPU basic metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Нагрузка на процессор +",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-(sum(rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$node\"}[$interval])) by (server) / sum(rate(node_cpu_seconds_total{ instance=~\"$node\"}[$interval])) by (server))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Сколько RAM всего",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": " {{server}} ram"
    }
   ]
  },
  {
   "title": "сколько GB RAM используется ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemFree_bytes{instance=~\"$node\"} ",
     "legendFormat": "{{server}} "
    }
   ]
  },
  {
   "title": "сколько процентов RAM используется ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemFree_bytes{instance=~\"$node\"}) / node_memory_MemTotal_bytes{instance=~\"$node\"}) ",
     "legendFormat": "{{server}} "
    }
   ]
  },
  { "title": "Disks metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "IO delay процессора",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(node_cpu_seconds_total{mode=\"iowait\",instance=~\"$node\"}[$interval])) by(server)/ sum(increase(node_cpu_seconds_total{instance=~\"$node\"}[$interval])) by(server)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Utilization/%",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=~\"$node\",device=~\"$disk\"}[$interval])",
     "legendFormat": "{{server}} Диск: {{device}}"
    }
   ]
  },
  {
   "title": "Скорость записи/СЕК",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{device=~\"$disk\",instance=~\"$node\"}[$interval])",
     "legendFormat": "{{server}}. Диск: {{device}}"
    }
   ]
  },
  {
   "title": "Скорость чтения/СЕК",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=~\"$disk\",instance=~\"$node\"}[$interval])",
     "legendFormat": "{{server}}. Диск: {{device}}"
    }
   ]
  },
  {
   "title": "Задержка записи/СЕК",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(node_disk_write_time_seconds_total{instance=~\"$node\",device=~\"$disk\"}[$interval])  or 0/ rate(node_disk_writes_completed_total{instance=~\"$node\",device=~\"$disk\"}[$interval])\r\n\r\n",
     "legendFormat": "{{server}}. Диск: {{device}}"
    }
   ]
  },
  {
   "title": "Задержка чтения/СЕК",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{instance=~\"$node\",device=~\"$disk\"}[$interval])  or 0 / rate(node_disk_reads_completed_total{instance=~\"$node\",device=~\"$disk\"}[$interval])\r\n\r\n",
     "legendFormat": "{{server}}. Диск: {{device}}"
    }
   ]
  },
  {
   "title": "FS free space / Свободное место",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{instance=~\"$node\",fstype=~\"zfs|ext4\"}",
     "legendFormat": "{{server}} - {{mountpoint}}"
    }
   ]
  },
  {
   "title": "FS used space / Занятое место",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$node\",fstype=~\"zfs|ext4\"} - node_filesystem_free_bytes{instance=~\"$node\",fstype=~\"zfs|ext4\"} ",
     "legendFormat": "{{server}} - {{mountpoint}}"
    }
   ]
  }
 ]
}